spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/Community?serverTimezone=UTC&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    open-in-view: false

  session:
    store-type: redis
    redis:
      namespace: shboard:session

  data:
    redis:
      host: localhost
      password: 'gustjq3735!'
      port: 6379

  profiles:
    active: custom-security

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID

auth:
  type: session

jwt:
  access:
    secret: c2NhcmVkYWdlZmVhdGhlcnNwbGVudHlyZWFkeWVhdHByaW5jaXBhbHJpc2Vwcm9iYWI=
    expiration: 900000
  refresh:
    secret: d2hvbGVtYWlucG9yY2hsb29rZWFyZ3JlYXRseXNoaW5lcmVzdHRlbGxuZWVkbGVrZXA=
    expiration: 604800000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG