spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/Community?serverTimezone=UTC&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG

  profiles:
    active: custom-security  # 또는 spring-security

  session:
    store-type: redis
    redis:
      namespace: shboard:session

  data:
    redis:
      host: localhost
      password: 'gustjq3735!'
      port: 6379


server:
  port: 8080
  servlet:
    session:
      cookie:
        name:
          JSESSIONID


auth:
  type: session  # jwt or session


jwt:
  access:
    secret: aGVsbG93b3JsZGhlbGxvd29ybGRoZWxsb3dvcmxkaGVsbG93b3JsZGhlbGxvd29ybGQ
    expiration: 900000  # 15분 = 15 * 60 * 1000
  refresh:
    secret: cmVmcmVzaHNlY3JldGtleWZvcmp3dHRva2VucmVmcmVzaHNlY3JldGtleWZvcmp3dA
    expiration: 604800000  # 7일 = 7 * 24 * 60 * 60 * 1000




